### ISSUE TITLE
Other players not getting paid.

### ISSUE THREAD

**Issue by igobythisname** [jhowkNx/Heist-Control-v2#16]
Issue is with at least the last 2 releases (2.18, 2.17, maybe 2.16 as well); i'm using automated presets>common presets>Quick Preset for cayo perico and insta-play presets for diamond casino; i only reset to default and then select the preset before starting each heist; issue is that other players are not getting any payout, whatsoever; i've been hosting heists with heist-control for many, many months, always either doing cayo perico or diamond casino and haven't had an issue until now; thanks in advance!

**Comment by igobythisname** [comment]
i just tried with 2.16; heist control was the only lua script i had loaded, no others, and still had the issue; ran cayo perico with automated presets>quick preset, myself and 1 other player, and the other player did not receive any payment at the end of the heist

**Comment by jhowkNx** [comment]
Hello,
I will check out these issues as soon as possible, thanks for letting me know.

**Comment by jhowkNx** [comment]
In the tests the [Quick Preset] preset worked well for the players, remember that this preset is unique too, it is not recommended to mix it with the others presets.
The same goes for Casino Heist, the tests went well. I didn't see any anomalies, if possible record a video of how you are doing this and send it to me.

**Comment by igobythisname** [comment]
Hi,
I don't mix any presets, i just use whatever one for the heist i'm hosting; i've been doing this for the past several months without issue, and now, ever since the update, i'm having issues.

before the diamond casino heist, i stand in front of the arcade garage door, i reset the heist to default, I select the insta-play preset, and i select the payout option in the advanced features; when the heist is completed, i turn off any options left on.  for the cayo perico heist, i stand outside the kosatka, i reset the heist to default, then I select the quick preset option.  i've never had to do anything else and everyone got $3.5m or $2.4m.

i've hosted several heists, casino and cayo, since the update and the other players who joined are not getting any payment at the end of the heist.  i'd love any help i can get please, thanks!

**Comment by igobythisname** [comment]
So... i stopped Resetting to Default before starting the heists and the issue went away! Hooray!! So, anyone who DOES Reset to Default must complete the heist first before other players can receive payment-which is fine for Cayo, it has one player option, but players are screwed on Casino, at least that first run after resetting to default.

**Comment by jhowkNx** [comment]
Hello, I am currently making changes to features that may affect Heist payment.
I will contact you soon to test a custom build with changes regarding the Cayo Perico Heist and Diamond Casino Heist

**Comment by jhowkNx** [comment]
This problem has been solved in the next version (2.19.0), thanks for your support!
