### ISSUE TITLE
Casino Heist Tunnel Glitch

### ISSUE THREAD

**Issue by votexxd** [jhowkNx/Heist-Control-v2#19]
Hi. Since a few weeks i encountered a glitch that, once halfway trough the tunnel it will bail the script user from the seasson / heist.
I have all protections in 2T1 disabled and i only selected the Silent & Sneaky approach insta-play preset + "the increase heist payout to 3.5mil for all" feature. 
As i already said, i encountered this glitch a few weeks ago. Back then it was quite rare and we could finish the heist very often without any problems. Since today tho it happens at every single approach i have tried (7 or 8 times). And the wierd thing is that i never changed anything in my heist config. 
I hope someone could help me with that problem as i realy love this script and would hate it to not being able to use it again.

**Comment by votexxd** [comment]
Update:
I tried it once more and this time it worked. This time tho i switched the outfit (preset heist outfit). Maybe thats what causing this issue but im not sure. I will try it a bit more and keep everyone witch that issue updated here

**Comment by jhowkNx** [comment]
Hello,
What you are reporting is an old Casino Heist bug, and it still happens to me, although it is very very rare.
From what I have been researching it is a desync issue that causes this disconnection, there is nothing I can do to prevent this.
 
You can see the tutorial that might help you:
https://www.reddit.com/r/gtaonline/comments/gqmy24/possible_fix_for_mantrap_disconnection_issue/
