### ISSUE TITLE
Casino and Island Heist

### ISSUE THREAD

**Issue by NutterButter690** [jhowkNx/Heist-Control-v2#2]
Hi, there. I installed the script and it shows v2 in the folder, but starting the script in the game it shows up as 1.4.1. Is this correct or is the wrong script loading even after I deleted the previous one? I have tried Casino and Island Heist with one other person, and both times I have encountered an issue. On the Casino heist, after opening the vault doors downstairs, my friend could pick up stuff but on my screen he wasn't moving. I couldn't pick stuff up either and eventually it just bugged out and the mission ended. This happened twice, I would t post in front of the gold and not do anything. I could do the safety deposit drill but no cash was showing up. On the Island heist, after going through the main doors my HUD disappeared and only my friend could interact with stuff. The enemies weren't hostile on me either and I couldn't do anything but kill myself. The only settings I turn on in the Heist Manager, is set up heist, and then I don't do anything else in the heist menu. The only other mods I've had on during this are god mode, unlimited ammo, and no recoil. However, I did the Island heist by myself and I got through without any bugs. It might just be bad bugs sometimes and good luck the other times. I did not pay the start up cost of the heist before I did the set up heist option (first one in Heist Manager under Casino and Island). I noticed after activating the script, it says to do so. Will it bug it that bad if the start up cost isn't paid and I try to set it all up anyway? Will everything be fine if I just pay the start up cost and resume like before?

**Comment by jhowkNx** [comment]
Hello.
Please check that there is not the old version in your downloads folder either, I checked and all the versions I shared are the latest versions. The v1 versions have been discontinued!

From what I saw in your report, your problem might be some kind of protection being blocked that appears a lot also when I am playing the Casino Heist is the "SE Spam" protection, even if deactivated this is still active and can cause problems in your heist.
It directly marks some people as modders and ends up blocking a list of scripts that negatively affect your heist.
What I can advise is that you check the list of members online, try to unmark them as modders and avoid having the problem freeze your character or some strange bug happen again.

If the problem persists, try to cancel the heist, pay the amount correctly and proceed with the methods available on HC. 

I'll leave this issue open for your feedback, thanks!

**Comment by NutterButter690** [comment]
> l

You were 100% right. I disabled all of that and all of your settings worked perfectly. I'm not sure how I overlooked that but thank you, it works perfectly.

**Comment by jhowkNx** [comment]
Awesome. 
Thanks for your feedback!
