### ISSUE TITLE
Skip missions not working

### ISSUE THREAD

**Issue by Inertia3141** [jhowkNx/Heist-Control-v2#23]

**Comment by jhowkNx** [comment]
Please be specific, that way I can't identify your problem.

**Comment by Inertia3141** [comment]
The skip Mrs. Baker option in the menu would not work for me for the longest time. I did eventually get it to work where I got a notification that popped up saying she left something for you at the docks but it took a bunch of tries in a bunch of different sessions. I think why it eventually worked is because I ended up doing the unlock all casino awards then doing the skip missions and then it worked.

**Comment by jhowkNx** [comment]
Hello,
When using the option to unlock achievements, you automatically receive the car (gift).
Although this function will be improved in the next version, thank you for your feedback!
