### ISSUE TITLE
Cayo Perico Heist - Preset Pink Diamond wrong objective

### ISSUE THREAD

**Issue by vcafezinho** [jhowkNx/Heist-Control-v2#3]
Dear Dev.

When selecting the Pink Diamond Preset (Solo), it instead displays Madrazzo Files as primary objective.

Also, taking the opportunity, I am not sure if is possible, but to give us the ability to choose what Secondary Objectives we want. Right now it fully populates or you can remove all.

Regards

**Comment by jhowkNx** [comment]
Hello.
I checked and noticed that both methods (normal and hard) have this bug, I will fix it as soon as possible and maybe tomorrow I will bring the fix to the public.
Thanks for reporting it!

**Comment by jhowkNx** [comment]
> Dear Dev.
> 
> When selecting the Pink Diamond Preset (Solo), it instead displays Madrazzo Files as primary objective.
> 
> Also, taking the opportunity, I am not sure if is possible, but to give us the ability to choose what Secondary Objectives we want. Right now it fully populates or you can remove all.
> 
> Regards

Hey there!
I checked and noticed that both methods (normal and hard) have this bug, I will fix it as soon as possible and maybe tomorrow I will bring the fix to the public.
Thanks for reporting it!

**Comment by vcafezinho** [comment]
Thanks jhowkNx !

Quick question about that 15 minute message. Should I wait 15 minutes after the Heist ended, can I start a new one as soon as Pavel tells me so? Thanks for the amazing work! Regards!

**Comment by jhowkNx** [comment]
> Thanks jhowkNx !
> 
> Quick question about that 15 minute message. Should I wait 15 minutes after the Heist ended, can I start a new one as soon as Pavel tells me so? Thanks for the amazing work! Regards!

You must wait 15 minutes when spawning on the map after completing the heist, the maximum payout of 2.5mi has a 15 minute cooldown to the next payout. Attempting to play (repeat) below this will cause you not to receive the payout!

**Comment by jhowkNx** [comment]
An updated version has been released with the Pink Diamond fix. I will be closing this issue in the next 24 hours.
If you find something wrong again, please report it as soon as possible.
Thanks a lot for your feedback!
