### ISSUE TITLE
》》Heist Control v2.22.1

### ISSUE THREAD

**Issue by Topnotchhomie** [jhowkNx/Heist-Control-v2#32]
Percentages heists pay outs not working

**Comment by jhowkNx** [comment]
Hello, which heist are you talking about?

**Comment by Topnotchhomie** [comment]
Sent diamond casino and cayob
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Topnotchhomie** [comment]
Discord casino heists also Cayo pierco

**Comment by jhowkNx** [comment]
Are you sure you are running v2.22.1? 
Make sure to enable all trusted mode variations
 - Stats
 - Global
 - Native

**Comment by jhowkNx** [comment]
You need Trusted mode to be activated all the time for it to make these changes

**Comment by Topnotchhomie** [comment]
I enable all trusted mode options or the Lua script won't open Are you sure you are running v2.22.1 yes latest version that's why I'm asking for a new hot fix or a update are you seeing that the cuts are working on your end it used to work because all I do is do these modded heists
Made sure to enable all trusted mode variations

Stats
Global
Native
 And when there enabled the Lua script is able to open and use the Lua script so without enabled the Lua script trusted mode disabled won't work i know that, when I have trusted mode all enabled and I load the diamond no cut percentages

**Comment by jhowkNx** [comment]
I'll take a look as soon i get a bit more of time to check, will answer you back. Thanks for reporting

**Comment by jhowkNx** [comment]
I just checked and didn't notice any anomalies at the moment, which casino preset did you specifically test?

**Comment by Topnotchhomie** [comment]
Casino preset of lowest buyer and $3,500,000 each just is 60% or 100% for myself don't seem to be working like it was when it was paying huge amounts like $3,500,000.

**Comment by Topnotchhomie** [comment]
102% was working before but I don't see it anymore.

**Comment by jhowkNx** [comment]
Are you in-game now? If yes please add me on discord: jhowkNx#5952

**Comment by Topnotchhomie** [comment]
I get off work at 7:00pm it'd 6:27pm I will be off headed online around 7:00am Topnotchhomie#3039 my discord.

**Comment by jhowkNx** [comment]
Solved: _User was reloading the menu during the heist, which affects the payment as it disables the loop._
