### ISSUE TITLE
unlock trophies for contract

### ISSUE THREAD

**Issue by ham1tcagdas** [jhowkNx/Heist-Control-v2#34]
it doesnt unlock trophies if even i->
first complete all missions i select and then
unlock all trophies rewards i select.
and i finish missions.
trophies are visible until i change session and they disappears and starts from zero. like contract office new purchased.

**Comment by ham1tcagdas** [comment]
also i applied those:

When playing missions, the following protections should be disabled entirely to avoid bugs and other issues:

- Block Attachments
- Block Cage Objects
- Block Collectible Drops
- Modder Detection → SE Spam
- Event Hooks > Script Events > Everything
- Event Hooks > Network Events > Everything (Use the "Disable All Net Event Hooks" feature at the top of the list)
- Miscellaneous > Disable Phone Calls

**Comment by jhowkNx** [comment]
This bug has been fixed in the next version [2.24.0], thanks for reporting.
