### ISSUE TITLE
heist board glitched

### ISSUE THREAD

**Issue by livsmonster** [jhowkNx/Heist-Control-v2#39]
when selecting heist control options *any the heist board glitches to show city backdrop and you cant change anything to launch the mission

**Comment by jhowkNx** [comment]
Hello, which heists are you talking about?
Tell me in detail so that I can check your problem. :)

**Comment by Zackattack2356** [comment]
i have the same problem. when i try to do the diamond heist "aggravated" it glitches the board and when i try to set it up the board disappears and the other players are getting normal pay rate

**Comment by jhowkNx** [comment]
Which version are you guys currently using?

**Comment by livsmonster** [comment]
Yea, if I use the 3.5 mill option for diamond or gold for casino heist it will glitch the heist board, using v2.26.0

**Comment by jhowkNx** [comment]
Use the newest one which atm is 2.27.0

**Comment by livsmonster** [comment]
oh man sorrythank

**Comment by Zackattack2356** [comment]
Mine works now

**Comment by jhowkNx** [comment]
> ok where do i find the newest version? when I download the file its the same old version

https://github.com/jhowkNx/Heist-Control-v2/releases/tag/2.27.0
