### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by ZynxXCandy** [jhowkNx/Heist-Control-v2#42]
I moved the lua script file to the script folder in 2take1 menu. And enabled all the"trusted mode" things, and it still doesn't work.

**Comment by ZynxXCandy** [comment]
> I moved the lua script file to the script folder in 2take1 menu. And enabled all the"trusted mode" things, and it still doesn't work.

What do I do with the "scripts.ink" shortcut file.

**Comment by ZynxXCandy** [comment]
> > I moved the lua script file to the script folder in 2take1 menu. And enabled all the"trusted mode" things, and it still doesn't work.
> 
> What do I do with the "scripts.ink" shortcut file. 

I put the Lua file in scripts > lib >

**Comment by jhowkNx** [comment]
Files with the .lua extension must be added to the scripts folder not lib
