### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by garfield025** [jhowkNx/Heist-Control-v2#46]
hello good, it does not work correctly, it is making me TP all the time without possibility to cancel it when loading the script
![image](https://user-images.githubusercontent.com/5413860/182478368-d835da93-a633-4de3-b49e-e0527f47d147.png)

**Comment by jhowkNx** [comment]
Hello,
Can you give details on how this happened/occurs?
What function did you use to make this happen?
Were you using some other script along with this one?

**Comment by garfield025** [comment]
I had previously loaded and activated "Keks' menu", "2take1Script", and finally "Heist Controlv2" version 2.27, I got the message to update, I did it, and as I went from 2.27 to 2.27.1, I got the message again for 2.28, and there I did tp automatically after doing "reset state" and load your script.

**Comment by garfield025** [comment]
When I restarted the game, it didn't happen again, I don't know if it's a failure of loading several scripts at the same time

**Comment by jhowkNx** [comment]
It must be something when loading the script, some interference from some other.
I will keep looking into it, anything if you find out let me know.

**Comment by garfield025** [comment]
Okay, I close thread
