### ISSUE TITLE
Heist Control Crashing on Startup.

### ISSUE THREAD

**Issue by LegendModzYT** [jhowkNx/Heist-Control-v2#50]
I don't exactly know what causes this but it has happened to me a couple of times, when loading heist control then quitting the game when I load the game back up again and inject 2Take1 the game crashes then once removing Heist Control from the scripts folder and load the game back up again, without Heist control in the scripts folder, injecting works fine. This isn't too bad a bug as it's easy to fix, jus remove Heist Control from scripts then put it back in when needed or jus make sure its unloaded when quitting the game.

**Comment by jhowkNx** [comment]
Hello,
Are you using an autoexec?
Check that you are also using an updated version to make sure nothing gets out of hand.

**Comment by LegendModzYT** [comment]
I was using Proddy's Autoexec. At the time I was using `Heist Control v2.29.1` although when able I will try updating it with `v2.29.2`.
