### ISSUE TITLE
Instant Finish Suddenly Stopped Working In Both Casino and Cayo Heists

### ISSUE THREAD

**Issue by kitkatyy** [jhowkNx/Heist-Control-v2#51]
Two days ago I ran Casino - Aggressive Gold and Instant Finished when I left the garage and it worked fine, completed and awarded payouts.
Then followed up with a Cayo - Quick Heist (Panther Only) and did an Instant Finish right outside the Submarine and it worked fine.
Yesterday I tried Casino Instant Finish again but the screen only flashed - I lost access to both my minimap and start menu for about 30 seconds) and had to manually finish the heist.
After that, ran Cayo and Instant Finished fine as before.
Today, neither Heists will Instant Finish and had to manually finish them. (The screen flashes as if it's trying to finish the heist, but then returns to continue playing the game/heist)
Was wondering what could be causing this issue?

**Comment by jhowkNx** [comment]
Hello,
An update has been sent out to lessen the impact of bugs, but it's a gta thing, unfortunately we can't have that much control over it.
If you experience bugs with the instant finish I recommend you restart your heist and try again.
