### ISSUE TITLE
Weekly Doomsday Heist Event

### ISSUE THREAD

**Issue by igobythisname** [jhowkNx/Heist-Control-v2#55]
there is a doomsday heist event this week; i ran automated act i, the payout was like $3.8m, so no one got paid. so, should we just avoid doing doomsday this week? what is the advice? can the script be updated to support events on this heist? thanks!

**Comment by jhowkNx** [comment]
Hello,
Yes there was an event where it affected payments and it caused conflict with the presets, unfortunately, I couldn't add support in time for such an event. I will try to resolve this as soon as possible next time. Thank you for the patience
