### ISSUE TITLE
Daily objective Rewards

### ISSUE THREAD

**Issue by UnknownModderr** [jhowkNx/Heist-Control-v2#7]
From my testing every time you try to unlock these, you receive an error and it won't actually change anything

**Comment by jhowkNx** [comment]
Heyo, can you explain what kind of error did you receive?
This achievement resets every day, it never stays activated forever.

In my tests, it is doing well.

**Comment by UnknownModderr** [comment]
Whenever I unlock them I get an error, and it does not unlock them for me either

**Comment by jhowkNx** [comment]
Hello, I would like to alert you that in my tests and even in a new account this function is working normally, I will be closing this case as solved, since no proof was presented showing the error.
