### ISSUE TITLE
Readme not update with new features

### ISSUE THREAD

**Issue by igobythisname** [jhowkNx/Heist-Control-v2#8]
hi, why isn't the Readme here updated with the new features? i want to read about how the Players Cut works, and all the other new features

**Comment by jhowkNx** [comment]
Hello.
I have been adding certain new things to the readme, of course I intend to improve it further in the future as soon as more time is available.
Thank you for understanding

**Comment by igobythisname** [comment]
Thanks for all your hard work and efforts, keep it up!!!
